language: php
php:
  - "5.6"
  - "7.0"
  - "7.1"

before_script:
  - composer install
script:
  - ./vendor/bin/phpunit tests/

notifications:
  emails:
    - asiagohan34@gmail.com
  on_success: always # default: change
  on_failure: always
